---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wfp.name" . }}
  labels:
    {{- include "wfp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "wfp.selectorLabels" . | nindent 4 }}