language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
before_deploy:
  - mv build workforce-profiles
  - tar -caf workforce-profiles.tar.gz workforce-profiles/*
deploy:
  provider: releases
  api_key:
    secure: DEda/upuvzR+VFqJzF6vMfk+PYYwIDVy+t0vOOrxvYE+32CR1iaZK8lKBEFqyVVYPX1bVR+jB5u6kIK0g5OezyVgHlGd/IvCVKnjEFu7HjDmoJ3+cg1AlYKCktxeKiV3TIdcuBf1OtMXZDH5FS9gYchwIqzjazsGRzHIT6jJ13jWel/fMj1VTQeNmPX6tVXlUVd6VHc2Ckt/F37X0GdKm06iHB+fnb/Up/8ovPWN1CXOQW9UfOJofmSSA0AG6Gok75yqW4z5xPQ9CRG4uS9qnp8s2vfNFKk3sQ6edSD+1xRpxAU3lHl3Yi16h+pFaCM3RkZS6/GsH3wN/bx//ZpYqbCGB7F66Se6Pdpe15B7ubdeR6UOu3luKNm87W4F0mleQHcSYIzflv1JV/eB10jobtzEybRx1wKYbmka7slnLVn0OjIi6RZipuN0jIdWm0uQd5yYIgOd4ygCLHZrEAjaFcHNE4KqAdy+9xrfEcWIYzpyM5oYETM2CbGyy1dpgZwNMmY0OTvpDvxUdZUkNBFaHcyU80qONibNPqIQYCP1glGtE49djqMa4S9E8SyLSNz/IGuxbWsgP8QfrFlCnBxjHwscIbLh93d2spROa3ZhMbxUXzHz4eyDSeNeaELaf4/o0x3aj1Ru6Tub3sYgN8h5HSORZlV5KJnLmGzZc7KjqDg=
  skip_cleanup: true
  file: workforce-profiles.tar.gz
  on:
    branch: master
    tags: true
