{{- if .Values.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: {{ include "wfp.fullname" . }}
    labels:
        {{- include "wfp.labels" . | nindent 4}}
spec:
    host: {{ .Values.route.host | quote }}
    tls:
        termination: {{ .Values.route.tls.termination }}
        insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    port:
        targetPort: {{ .Values.service.portName }}
    to:
        kind: Service
        name: {{ include "wfp.name" . }}
        weight: 100
    wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- end}}