name: Deploy to Environment
description: Deploys an image to the defined environment
inputs:
  app_name:
    description: Application general Name
    required: true
  acronym:
    description: Application acronym
    required: true
  environment:
    description: Logical Github Environment
    required: true
  job_name:
    description: Job/Instance name
    required: true
  namespace_prefix:
    description: Openshift Namespace common prefix
    required: true
  openshift_server:
    description: Openshift API Endpoint
    required: true
  openshift_token:
    description: Openshift Service Account Token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/redhat-actions/oc-login
    - name: Login to OpenShift Cluster
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ inputs.openshift_server }}
        openshift_token: ${{ inputs.openshift_token }}
        insecure_skip_tls_verify: true
        namespace: ${{ inputs.namespace_prefix }}-${{ inputs.environment }}

    - name: Add SHORT_SHA env property with commit short sha
      id: shavar
      shell: bash
      run: echo "short_sha=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Helm Deploy
      shell: bash
      run: >-
        helm upgrade --install --atomic ${{ inputs.job_name }} ./charts/${{ inputs.app_name }}
        --namespace ${{ inputs.namespace_prefix }}-${{ inputs.environment }}
        --set route.host=${{ inputs.app_name }}-${{ inputs.namespace_prefix }}-${{ inputs.environment }}.apps.silver.devops.gov.bc.ca
        --set image.tag=${{ steps.shavar.outputs.short_sha }}
        --values ./charts/wfp/values.${{ inputs.environment }}.yaml
        --timeout 10m
        --wait

    - name: Wait on Deployment
      shell: bash
      run: |
        oc rollout --namespace ${{ inputs.namespace_prefix }}-${{ inputs.environment }} status deployment/${{ inputs.app_name }} --watch=true