name: Push

env:
  APP_NAME: wfp
  ACRONYM: wfp

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  codeql:
    uses: ./.github/workflows/codeql-analysis.yml

  build:
    name: Build & Push
    needs: codeql
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push
        uses: ./.github/actions/build-push-container
        with:
          context: .
          image_name: ${{ env.APP_NAME }}
          image_registry: ${{ secrets.IMAGE_REGISTRY }}
          image_registry_user: ${{ secrets.IMAGE_REGISTRY_USER }}
          image_registry_password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

  deploy-dev:
    name: Deploy to Dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Dev
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: dev
          job_name: dev
          namespace_prefix: ${{ secrets.NAMESPACE_PREFIX }}
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-test:
    name: Deploy to Test
    environment:
      name: test
    runs-on: ubuntu-latest
    needs: 
      - build
      - deploy-dev
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Test
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: test
          job_name: test
          namespace_prefix: ${{ secrets.NAMESPACE_PREFIX }}
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-prod:
    name: Deploy to Prod
    environment:
      name: prod
    runs-on: ubuntu-latest
    needs: 
      - build
      - deploy-dev
      - deploy-test
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Prod
        uses: ./.github/actions/deploy-to-environment
        with:
          app_name: ${{ env.APP_NAME }}
          acronym: ${{ env.ACRONYM }}
          environment: prod
          job_name: prod
          namespace_prefix: ${{ secrets.NAMESPACE_PREFIX }}
          openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}